stages:
  - deploy

image: node:lts-alpine

cache:
  paths:
    - node_modules/

before_script:
  - yarn install --frozen-lockfile

pages:
  stage: deploy
  script:
    - yarn export
  after_script:
    - mv __sapper__/export/$CI_PROJECT_NAME public
  artifacts:
    paths:
      - public/
  only:
    - main
