name: CI

on: push

env:
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  GH_CONTAINER_IMAGE_REGISTRY: ghcr.io

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          buildah bud --format=docker \
            --label org.opencontainers.image.title="$CONTAINER_IMAGE_NAME" \
            --label org.opencontainers.image.description="${{ github.event.repository.description }}" \
            --label org.opencontainers.image.url="${{ github.event.repository.html_url }}" \
            --label org.opencontainers.image.source="${{ github.event.repository.html_url }}" \
            --label org.opencontainers.image.version="latest" \
            --label org.opencontainers.image.created="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --label org.opencontainers.image.revision="${{ github.sha }}" \
            --label org.opencontainers.image.licenses="${{ github.event.repository.license.spdx_id }}" \
            -t $CONTAINER_IMAGE_NAME .

      - name: Push To GitHub Registry
        uses: redhat-actions/push-to-registry@v1
        with:
          image: $CONTAINER_IMAGE_NAME
          registry: $GH_CONTAINER_IMAGE_REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}